### ISSUE TITLE
I can't use monitor mode

### ISSUE THREAD

**Issue by leonpano2006** [lwfinger/rtl8852au#4]
Error to enable monitor mode in fern Wi-Fi cracker

**Comment by lwfinger** [comment]
I do not plan to waste any time adding features to that ugly pile of code. If you really need the feature, then you will need to add it yourself.

**Comment by leonpano2006** [comment]
How to do?

**Comment by leonpano2006** [comment]
Can you at least tell me how to add that code?
If you don't want to add that

**Comment by lwfinger** [comment]
It is not that easy, which is why I have not added it. You need to modify the driver to report to mac80211 that it supports monitor mode, and then write the routines needed to implement the feature. The Realtek authors have just app the code needed for AP operation. Perhaps you should file a feature request for them to implement monitor mode.

**Comment by leonpano2006** [comment]
Fixed by https://github.com/leonpano2006/rtl8852au
(You just need to change one letter from n to y to make it work)

**Comment by mitsukuri** [comment]
@leonpano2006, the link is 404 as of now.
If you're still around, could you please give a heads-up about the location of said fix?

**Comment by leonpano2006** [comment]
Is already merged 
That link is not needed
